Fix and improve "Show PID/TID in HEX" feature
x64dbg/x64dbg pull request #2987
Opened 2022-12-03 04:47 UTC by not6

There's still a lot of improvements that could be made, where the PID/TID is always hexadecimal, but this was the worst one IMO.

2022-12-03 22:35 UTC, mrexodia requested changes

2022-12-03 22:35 UTC, mrexodia commented on src/dbg/debugger.cpp
> -                sprintf_s(threadName2, "%X", PrevThreadId);
There is a function `formatpidtid` that does this

2022-12-03 22:35 UTC, mrexodia commented on src/dbg/debugger.cpp
> -    if(settingboolget("Gui", "PidInHex"))
Same, it can be switched to the function `formatpidtid`

2022-12-04 23:38 UTC, not6 commented
@mrexodia Should be good now

2022-12-06 10:35 UTC, mrexodia approved these changes

2022-12-06 10:36 UTC, merged

2022-12-06 10:36 UTC, mrexodia commented
Awesome, thanks a lot!