changed the font size in for issue 2598 problem no 5
x64dbg/x64dbg pull request #2989
Opened 2022-12-05 21:24 UTC by taher-mulla

I have worked on Issue#2598 and have changed the font size in the box for it to 20px.

2022-12-06 10:33 UTC, mrexodia requested changes

2022-12-06 10:33 UTC, mrexodia commented on bin/themes/Dark/style.css
> -    color: #EF5350;
With all these whitespace changes it's not possible to see what you actually changed. Please configure your editor to not reformat the whole file.

2022-12-06 10:33 UTC, mrexodia commented on bin/themes/Dark/style.css
> +  font-size: 20px;
I'm not sure if you should change all the `QLineEdit`. Perhaps instead set the font size in the calculator directly...

2022-12-07 01:33 UTC, taher-mulla commented
I have changed the .css file. I have also added the font size to 4. The default should be 3 according to what I see online.

2023-02-23 00:38 UTC, mrexodia commented
Thank you, but this is not fixing the issue because font size 4 looks super small on my screen. Likely the fix would involve using the 'default+x%' font size based on the user's CSS but it is too minor for me to spend a lot of time on.

I'll close this for now, feel free to create a new PR.

2023-02-23 00:38 UTC, closed without merging