Sort by status in symbols tab
x64dbg/x64dbg pull request #3313
Opened 2024-02-17 08:24 UTC by mobile46

2024-02-17 09:13 UTC, mrexodia requested changes

2024-02-17 09:13 UTC, mrexodia commented on src/gui/Src/Gui/SymbolView.cpp
> +        setCellContent(r, c, QString::number(status));
This should be set when the symbols are populated instead.

2024-02-19 22:34 UTC, mrexodia commented
What exactly doesn't work about sorting the status? It seems to work fine for me...

2024-02-20 06:02 UTC, mobile46 commented
No, it's not sorting correctly. It's sorting by the previously selected row. Please see attached gif.

![x64dbg_HnYwYVGRkN](https://github.com/x64dbg/x64dbg/assets/8193734/3424ab73-ee39-406e-b76f-36586bdf3dd5)

2024-02-20 09:15 UTC, mrexodia commented
Lol my bad, I was testing the symbols tab 🤦‍♂️

2024-03-21 01:13 UTC, mrexodia commented
I'll get back to this btw, need to verify something before merging it.

2024-04-10 23:08 UTC, mrexodia commented
Finally had some time to investigate this and as I suspected there is an issue with the implementation. The sorting function always uses the text contents of the table, but in this case the table is 'virtual' and the symbol status isn't present. You add a number that represents the current status, but this is only done when the modules refresh.

If symbols are actually loaded, the displayed status is changed, but the number you set in the cell isn't updated. So this means you will just be sorting incorrectly in a different way.

Thanks for bringing this to my attention though, I will fix it and credit you in the commit.

2024-04-10 23:08 UTC, closed without merging